name       : imake
version    : 1.0.7
release    : 1
source     :
    - https://www.x.org/releases/individual/util/imake-1.0.7.tar.gz : 6bda266a07eb33445d513f1e3c82a61e4822ccb94d420643d58e1be5f881e5cb
license    : MIT
component  : programming
summary    : imake
description: |
    imake
builddeps  :
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
