name       : imake
version    : 1.0.9
release    : 11
source     :
    - https://www.x.org/releases/individual/util/imake-1.0.9.tar.gz : ca53ad18c683091490596d72fee8dbee4c6ddb7693709e25f26da140d29687c1
license    : MIT
component  : programming
summary    : Imake is used to generate Makefiles from a template, a set of cpp macro functions, and a per-directory input file called an Imakefile.
description: |
    Imake is used to generate Makefiles from a template, a set of cpp macro functions, and a per-directory input file called an Imakefile.
builddeps  :
    - pkgconfig(xproto)
rundeps    :
    - xorg-cf-files
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
